version: "3.7"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.simpleapp
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: djangodb
      MYSQL_USER: djangouser
      MYSQL_PASSWORD: djangopassword
