FROM alpine:3.8 as initialstatic
ENV PYTHONUNBUFFERED 1
RUN apk add python2 py2-django py-mysqldb

FROM initialstatic
WORKDIR /simpleapp
COPY . .
COPY wait-for /usr/local/bin/
CMD ["sh","-c","/usr/local/bin/wait-for db:3306 -- sh -c 'python manage.py makemigrations && python manage.py migrate && python manage.py loaddata initialstrings.json' && python manage.py runserver 0.0.0.0:80"]